---
title: "Model Metrics"
author: "Mohamed Hassan-El Serafi"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
metrics_table <- data.frame(
  Model = c("Ridge Regression",
            "Ridge Regression Modified Dataset",
            "Lasso Regression",
            "Lasso Regression Modified Dataset",
            "Elastic Net Regression",
            "Elastic Net Regression Modified Dataset",
            "Bayesian Linear Regression",
            "Bayesian Linear Regression Modified Dataset"),
  
  RMSE = round(c(ridge_results$RMSE[1],
                 ridge_results_modified$RMSE[1],
                 lasso_results$RMSE[1],
                 lasso_results_modified$RMSE[1],
                 en_results$RMSE[1],
                 en_results_modified$RMSE[1],
                 bayes_rmse, 
                 bayes_rmse_mod), 3),

  R_Squared = round(c(ridge_results$R_squared[1],
                      ridge_results_modified$R_squared[1],
                      lasso_results$R_squared[1],
                      lasso_results_modified$R_squared[1],
                      en_results$R_squared[1],
                      en_results_modified$R_squared[1],
                      NA,
                      NA), 3),

  Adjusted_R2 = round(c(ridge_results$Adjusted_R_squared[1],
                        ridge_results_modified$Adjusted_R_squared[1],
                        lasso_results$Adjusted_R_squared[1],
                        lasso_results_modified$Adjusted_R_squared[1],
                        en_results$Adjusted_R_squared[1],
                        en_results_modified$Adjusted_R_squared[1],
                        NA,
                        NA), 3)
)

```



```{r}
metrics_table
```



```{r}
# Create table using tableGrob function
table_grob <- tableGrob(metrics_table)

# Save as PNG
ggsave("model_metrics_table.png", plot = table_grob, width = 8, height = 3)
```



**The calculations made below are from the Bayesian models used with chains = 2 and iter = 1000. They can be found under the Bayesian_Reg_Modeling_Draft file, between lines 1247 to 1452.**


```{r}
R_squared_bayes
```


```{r}
adj_r2_bayes
```



```{r}
R_squared_bayes_modified
```


```{r}
adj_r2_bayes_modified
```







